'field_separator': "\t",
    'seq_separator': " ",
    'USER_ID_FIELD': 'user_id',
    'ITEM_ID_FIELD': 'item_id',
    'TIME_FIELD': 'timestamp',
    'user_inter_num_interval': "[5,inf)",
    'item_inter_num_interval': "[5,inf)",
    'load_col': {'inter': ['user_id', 'item_id', 'timestamp'],
                 'item': ['item', 'genre', 'title', 'year', 'writer', 'director']},
    'selected_features': ['genre', 'title', 'year', 'writer', 'director'],
    'NEG_PREFIX': 'neg_',
    'LABEL_FIELD': 'label',
    'ITEM_LIST_LENGTH_FIELD': 'item_length',
    'LIST_SUFFIX': '_list',
    'MAX_ITEM_LIST_LENGTH': 50,
    'POSITION_FIELD': 'position_id',
    'epochs': 50,
    'train_batch_size': 256,
    'learner': 'adam',
    'learning_rate': 0.001,
    'training_neg_sample_num': 0,
    'eval_step': 1,
    'stopping_step': 10,
    'eval_setting': 'TO_LS,full',
    'metrics': ["Recall", "MRR","NDCG","Precision"],
    'valid_metric': 'MRR@10',
    'eval_batch_size': 256,
    'weight_decay': 0,
    'topk': [5, 10, 20, 50],
    'log_root': "./log/",
    'lmd': 0.1,
    'lmd_sem': 0.1,
    'tau': 1,
    'contrast': 'us_x',
    'sim': 'dot',
    'hidden_dropout_prob': 0.5,
    'attn_dropout_prob': 0.5,
    'data_path': "./dataset/"