wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.13
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: train_step
    - 1: train/epoch
      5: 1
      6:
      - 1
    - 1: train/train_loss
      5: 1
      6:
      - 1
    - 1: valid_step
    - 1: valid/recall@10
      5: 4
      6:
      - 1
    - 1: valid/mrr@10
      5: 4
      6:
      - 1
    - 1: valid/ndcg@10
      5: 4
      6:
      - 1
    - 1: valid/hit@10
      5: 4
      6:
      - 1
    - 1: valid/precision@10
      5: 4
      6:
      - 1
    python_version: 3.8.5
    start_time: 1649386064
    t:
      1:
      - 1
      - 5
      - 36
      - 53
      - 55
      3:
      - 7
      - 16
      4: 3.8.5
      5: 0.12.13
      8:
      - 5
cmd_config_dict:
  desc: null
  value:
    log_wandb: true
dataset:
  desc: null
  value: recbox_data
external_config_dict:
  desc: null
  value:
    log_wandb: true
file_config_dict:
  desc: null
  value: {}
final_config_dict:
  desc: null
  value:
    ENTITY_ID_FIELD: entity_id
    HEAD_ENTITY_ID_FIELD: head_id
    ITEM_ID_FIELD: item_id
    ITEM_LIST_LENGTH_FIELD: item_length
    LABEL_FIELD: label
    LIST_SUFFIX: _list
    MAX_ITEM_LIST_LENGTH: 50
    MODEL_INPUT_TYPE: InputType.PAIRWISE
    MODEL_TYPE: ModelType.GENERAL
    NEG_PREFIX: neg_
    POSITION_FIELD: position_id
    RATING_FIELD: rating
    RELATION_ID_FIELD: relation_id
    TAIL_ENTITY_ID_FIELD: tail_id
    TIME_FIELD: timestamp
    USER_ID_FIELD: user_id
    additional_feat_suffix: null
    alias_of_entity_id: null
    alias_of_item_id: null
    alias_of_relation_id: null
    alias_of_user_id: null
    benchmark_filename: null
    beta: 0.2
    checkpoint_dir: saved
    clip_grad_norm: null
    data_path: dataset/recbox_data
    dataloaders_save_path: null
    dataset: recbox_data
    dataset_save_path: null
    device: cuda
    dropout_prob: 0.5
    epochs: 300
    eval_args:
      group_by: user
      mode: full
      order: RO
      split:
        RS:
        - 0.8
        - 0.1
        - 0.1
    eval_batch_size: 4096
    eval_neg_sample_args:
      distribution: uniform
      strategy: full
    eval_step: 1
    eval_type: EvaluatorType.RANKING
    field_separator: "\t"
    filter_inter_by_user_or_item: true
    gamma: 0.005
    gpu_id: 0
    hidden_dimension: 600
    item_inter_num_interval: '[0,inf)'
    latent_dimension: 200
    learner: adam
    learning_rate: 0.001
    load_col:
      inter:
      - user_id
      - item_id
    log_wandb: true
    loss_decimal_place: 4
    metric_decimal_place: 4
    metrics:
    - Recall
    - MRR
    - NDCG
    - Hit
    - Precision
    mixture_weights:
    - 0.15
    - 0.75
    - 0.1
    model: RecVAE
    n_dec_epochs: 1
    n_enc_epochs: 3
    neg_sampling:
      uniform: 1
    normalize_all: null
    normalize_field: null
    preload_weight: null
    repeatable: false
    reproducibility: true
    require_pow: false
    rm_dup_inter: null
    save_dataloaders: false
    save_dataset: false
    seed: 2020
    seq_len: null
    seq_separator: ' '
    show_progress: true
    state: INFO
    stopping_step: 10
    threshold: null
    topk:
    - 10
    train_batch_size: 2048
    train_neg_sample_args:
      by: 1
      distribution: uniform
      dynamic: none
      strategy: by
    unload_col: null
    unused_col: null
    use_gpu: true
    user_inter_num_interval: '[0,inf)'
    val_interval: null
    valid_metric: Recall@10
    valid_metric_bigger: true
    wandb_project: recbole
    weight_decay: 0.0
internal_config_dict:
  desc: null
  value:
    ENTITY_ID_FIELD: entity_id
    HEAD_ENTITY_ID_FIELD: head_id
    ITEM_ID_FIELD: item_id
    ITEM_LIST_LENGTH_FIELD: item_length
    LABEL_FIELD: label
    LIST_SUFFIX: _list
    MAX_ITEM_LIST_LENGTH: 50
    MODEL_TYPE: ModelType.GENERAL
    NEG_PREFIX: neg_
    POSITION_FIELD: position_id
    RATING_FIELD: rating
    RELATION_ID_FIELD: relation_id
    TAIL_ENTITY_ID_FIELD: tail_id
    TIME_FIELD: timestamp
    USER_ID_FIELD: user_id
    additional_feat_suffix: null
    alias_of_entity_id: null
    alias_of_item_id: null
    alias_of_relation_id: null
    alias_of_user_id: null
    benchmark_filename: null
    beta: 0.2
    checkpoint_dir: saved
    clip_grad_norm: null
    data_path: dataset/
    dataloaders_save_path: null
    dataset_save_path: null
    dropout_prob: 0.5
    epochs: 300
    eval_args:
      group_by: user
      mode: full
      order: RO
      split:
        RS:
        - 0.8
        - 0.1
        - 0.1
    eval_batch_size: 4096
    eval_step: 1
    field_separator: "\t"
    filter_inter_by_user_or_item: true
    gamma: 0.005
    gpu_id: 0
    hidden_dimension: 600
    item_inter_num_interval: '[0,inf)'
    latent_dimension: 200
    learner: adam
    learning_rate: 0.001
    load_col:
      inter:
      - user_id
      - item_id
    log_wandb: false
    loss_decimal_place: 4
    metric_decimal_place: 4
    metrics:
    - Recall
    - MRR
    - NDCG
    - Hit
    - Precision
    mixture_weights:
    - 0.15
    - 0.75
    - 0.1
    n_dec_epochs: 1
    n_enc_epochs: 3
    neg_sampling:
      uniform: 1
    normalize_all: null
    normalize_field: null
    preload_weight: null
    repeatable: false
    reproducibility: true
    require_pow: false
    rm_dup_inter: null
    save_dataloaders: false
    save_dataset: false
    seed: 2020
    seq_len: null
    seq_separator: ' '
    show_progress: true
    state: INFO
    stopping_step: 10
    threshold: null
    topk:
    - 10
    train_batch_size: 2048
    unload_col: null
    unused_col: null
    use_gpu: true
    user_inter_num_interval: '[0,inf)'
    val_interval: null
    valid_metric: Recall@10
    valid_metric_bigger: true
    wandb_project: recbole
    weight_decay: 0.0
model:
  desc: null
  value: RecVAE
model_class:
  desc: null
  value: recbole.model.general_recommender.recvae.RecVAE
parameters:
  desc: null
  value:
    Dataset:
    - field_separator
    - seq_separator
    - USER_ID_FIELD
    - ITEM_ID_FIELD
    - RATING_FIELD
    - TIME_FIELD
    - seq_len
    - LABEL_FIELD
    - threshold
    - NEG_PREFIX
    - ITEM_LIST_LENGTH_FIELD
    - LIST_SUFFIX
    - MAX_ITEM_LIST_LENGTH
    - POSITION_FIELD
    - HEAD_ENTITY_ID_FIELD
    - TAIL_ENTITY_ID_FIELD
    - RELATION_ID_FIELD
    - ENTITY_ID_FIELD
    - load_col
    - unload_col
    - unused_col
    - additional_feat_suffix
    - rm_dup_inter
    - val_interval
    - filter_inter_by_user_or_item
    - user_inter_num_interval
    - item_inter_num_interval
    - alias_of_user_id
    - alias_of_item_id
    - alias_of_entity_id
    - alias_of_relation_id
    - preload_weight
    - normalize_field
    - normalize_all
    - benchmark_filename
    Evaluation:
    - eval_args
    - repeatable
    - metrics
    - topk
    - valid_metric
    - valid_metric_bigger
    - eval_batch_size
    - metric_decimal_place
    General:
    - gpu_id
    - use_gpu
    - seed
    - reproducibility
    - state
    - data_path
    - checkpoint_dir
    - show_progress
    - config_file
    - save_dataset
    - dataset_save_path
    - save_dataloaders
    - dataloaders_save_path
    - log_wandb
    Training:
    - epochs
    - train_batch_size
    - learner
    - learning_rate
    - neg_sampling
    - eval_step
    - stopping_step
    - clip_grad_norm
    - weight_decay
    - loss_decimal_place
variable_config_dict:
  desc: null
  value: {}
yaml_loader:
  desc: null
  value: yaml.loader.FullLoader
