# dataset config
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
load_col:
  inter: [user_id, item_id, rating, timestamp]
  item: ['item_id', 'class'] # ['item_id', 'year', 'class'] 
MAX_ITEM_LIST_LENGTH: 50

user_inter_num_interval: None
item_inter_num_interval: None

# model config 
embedding_size: 64

# Training and evaluation config
epochs: 100
train_batch_size: 4096
eval_batch_size: 4096
neg_sampling:
    uniform: 1
eval_args:
    group_by: user
    order: TO
    split: {'RS': [8, 1, 1]}
    mode: full
eval_batch_size: 4096
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: 10
valid_metric: MRR@10
metric_decimal_place: 4

# Other Hyper Parameters
# loss_type: BPR
  